### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8008

### ISSUE THREAD

**Issue by toneehh** [ThaTiemsz/discord-butter#1]
```
D:\discord-butter-master>npm run start

> discord-butter@1.0.0 start D:\discord-butter-master
> electron main.js


(node:7432) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Error: connect ECONNREFUSED 127.0.0.1:8008
(node:7432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ RequestError: Error: connect ECONNREFUSED 127.0.0.1:8008
    at new RequestError (D:\discord-butter-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\discord-butter-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\discord-butter-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\discord-butter-master\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\discord-butter-master\node_modules\request\request.js:881:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 127.0.0.1:8008',
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:8008
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 8008 },
  error:
   { Error: connect ECONNREFUSED 127.0.0.1:8008
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 8008 },
  options:
   { method: 'POST',
     uri: 'http://127.0.0.1:8008',
     headers:
      { Authorization: 'cG9wY29ybjpwb3Bjb3Ju',
        Accept: 'application/json' },
     body: { id: 79, jsonrpc: '2.0', method: 'ping', params: [] },
     timeout: 3000,
     json: true,
     resolveWithFullResponse: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by ThaTiemsz** [comment]
Is this enabled and is the port set to 8008?

![image](https://user-images.githubusercontent.com/18150845/49596898-a8051880-f97b-11e8-97df-e88d1cdd6a83.png)

**Comment by toneehh** [comment]
I was apparently using a different version of Popcorn Time that didn't have such settings. Fixed!
